-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admins
(
    admin_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_order_accept boolean DEFAULT true,
    CONSTRAINT admins_pkey PRIMARY KEY (admin_id),
    CONSTRAINT admins_email_key UNIQUE (email),
    CONSTRAINT admins_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    phone character varying(15) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    dob date,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.menu_category
(
    category_id serial NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT menu_category_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.menu_items
(
    item_id serial NOT NULL,
    item_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    category_id integer,
    price numeric(10, 2) NOT NULL,
    image_url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    is_available boolean DEFAULT true,
    CONSTRAINT menu_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id serial NOT NULL,
    order_id integer,
    item_id integer,
    quantity integer NOT NULL,
    price numeric(10, 2) NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    order_id serial NOT NULL,
    customer_id integer,
    table_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    total_amount numeric(10, 2) DEFAULT 0,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    order_id integer,
    amount numeric(10, 2),
    payment_status character varying(20) COLLATE pg_catalog."default",
    payment_method character varying(50) COLLATE pg_catalog."default",
    razorpay_payment_id character varying(200) COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    rating_id serial NOT NULL,
    customer_id integer NOT NULL,
    rating_value integer NOT NULL,
    review_text text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id integer,
    order_id integer,
    CONSTRAINT ratings_pkey PRIMARY KEY (rating_id),
    CONSTRAINT unique_customer_item_rating UNIQUE (customer_id, item_id),
    CONSTRAINT unique_customer_order_rating UNIQUE (customer_id, order_id)
);

COMMENT ON TABLE public.ratings
    IS 'Customer ratings and reviews - normalized design with customer_id reference only';

COMMENT ON COLUMN public.ratings.rating_id
    IS 'Primary key - unique rating identifier';

COMMENT ON COLUMN public.ratings.customer_id
    IS 'Foreign key to customers table - one rating per customer';

COMMENT ON COLUMN public.ratings.rating_value
    IS 'Rating value from 1 to 5 stars';

COMMENT ON COLUMN public.ratings.review_text
    IS 'Optional text review from customer';

COMMENT ON COLUMN public.ratings.created_at
    IS 'Timestamp when rating was created';

CREATE TABLE IF NOT EXISTS public.sessions
(
    session_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    customer_id integer,
    ip_address character varying(45) COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    last_activity timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id serial NOT NULL,
    admin_id integer,
    CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.menu_items
    ADD CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.menu_category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_menu_items_category
    ON public.menu_items(category_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.menu_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_order_items_item_id
    ON public.order_items(item_id);


ALTER TABLE IF EXISTS public.order_items
    ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON public.order_items(order_id);


ALTER TABLE IF EXISTS public.orders
    ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_orders_customer_id
    ON public.orders(customer_id);


ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_payments_order_id
    ON public.payments(order_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_customer FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_customer_id
    ON public.ratings(customer_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_item FOREIGN KEY (item_id)
    REFERENCES public.menu_items (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_item_id
    ON public.ratings(item_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT fk_ratings_order FOREIGN KEY (order_id)
    REFERENCES public.orders (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ratings_order_id
    ON public.ratings(order_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT fk_sessions_admin FOREIGN KEY (admin_id)
    REFERENCES public.admins (admin_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_admin_id
    ON public.sessions(admin_id);


ALTER TABLE IF EXISTS public.sessions
    ADD CONSTRAINT sessions_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_customer_id
    ON public.sessions(customer_id);

END;